apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nintendo
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
images:
  - name: ghcr.io/nintendovibes/joy-con-readers
    newTag: 051dd4855dd9e50e8c3bbc071a00c1b850b6d51c # CI overwrites this with the commit SHA on every build
