apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nintendo
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
images:
  - name: ghcr.io/nintendovibes/joy-con-readers
    newTag: b8ac2a94896db57bd1e16633b31b80689e41d093 # CI overwrites this with the commit SHA on every build
