apiVersion: v1
kind: Service
metadata:
  name: joy-con-readers
  labels:
    app: joy-con-readers
spec:
  selector:
    app: joy-con-readers
  ports:
    - name: http
      port: 8080
      targetPort: http
