apiVersion: v1
kind: Service
metadata:
  name: joycon-reader
  labels:
    app: joycon-reader
spec:
  selector:
    app: joycon-reader
  ports:
    - name: http
      port: 8080
      targetPort: http
